# Generated by Django 2.2.5 on 2019-09-27 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mptt_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='owner',
            field=models.CharField(default='vamme', max_length=50),
        ),
    ]
